iina/iina

iina/Info.plist
iina/VideoView.swift

Some older cards may not support this but this works for me on mid-2012 rMBP.

Allow using integrated GPU to play videos, fix #18.

---

iina/MPVController.swift

Previously, path like `~/.config/mpv` won't be recognized in the
advanced settings. This fixes such issue.

resolve path for userConfigDir in the advanced settings

---

CONTRIBUTING.md
README.md
iina.xcodeproj/project.pbxproj
iina/AppData.swift
iina/Base.lproj/AboutWindowController.xib
iina/Base.lproj/MainMenu.xib
iina/Base.lproj/PrefAdvancedViewController.xib
iina/Base.lproj/PrefGeneralViewController.xib
iina/Base.lproj/PrefKeyBindingViewController.xib
iina/Base.lproj/PrefSubViewController.xib
iina/Base.lproj/PrefUIViewController.xib
iina/Base.lproj/QuickSettingViewController.xib
iina/MPVController.swift
iina/MainWindowController.swift
iina/OSDMessage.swift
iina/PlayerCore.swift
iina/QuickSettingViewController.swift
iina/Utility.swift

There's quite a bit of unrelated things in this pull request, so I'll go through it one by one:
1. Indentation enforcement to 2 spaces via project file: I turned this on to assist those who aren't accustomed to 2 space indents (like me!)
2. Rewording some settings, README.md, and CONTRIBUTING.md to sound better in my (very often flawed) opinion and to better match macOS's wording
3. Force Touch support for the arrow keys, made to match QuickTime Player as closely as possible. One exception is that clicking multiple times goes from
```
1x → 2x → … → 32x → 1x → 2x → …
```
instead of QuickTime Player's
```
1x → 2x → … → 32x → 2x → …
```
This was to be consistent with previous versions of IINA.
4. I have remapped the available playback speeds from (-∞, -1] ∪ [1, ∞) to (0, ∞). I've put a lot …

Grammatical fixes, remap speed, and Force Touch for fast-forward/rewinding

---

iina/zh-Hans.lproj/PrefSubViewController.strings

- ObjectID of “Download subtitles from:” is wrong in the localization
file.
Also a friendly ping to @shilch, it seems you missed this label 😃

Fix the wrong ObjectID

---

iina/AboutWindowController.swift
iina/Base.lproj/AboutWindowController.xib
iina/Base.lproj/InspectorWindowController.xib
iina/Base.lproj/MainWindowController.xib
iina/Base.lproj/PlaylistViewController.xib
iina/Base.lproj/PrefKeyBindingViewController.xib
iina/Base.lproj/QuickSettingViewController.xib
iina/MPVController.swift
iina/MPVFilter.swift
iina/MPVTrack.swift
iina/MainWindowController.swift
iina/PlayerCore.swift
iina/PlaylistViewController.swift
iina/PrefKeyBindingViewController.swift
iina/Preference.swift
iina/QuickSettingViewController.swift
iina/Utility.swift
iina/ViewLayer.swift

#366 
@saagarjha Please take a look.
**1. Basically reset `QuickSettingsView` to `develop` version, but added required constraints**
There's no need for more auto layout in `QuickSettingsView`, at least for document icon feature.
**2. Changed back to fixed sidebar width.**
By using `fittingSize.width`, sidebar's width will depend on  its subviews' width, and to adjust sidebar width, we must change internal constraints of subviews, which didn't fully utilize auto layout. So my opinion on sidebar resize:
- `PlaylistView` and `QuickSettingsView` should fit their superview's width, and then WindowController set explicit width value for sidebar.
- All width changing and restoring are handled based on sidebar's width.
- `SidebarViewType#width` should be reserved for a unified interface. …

Document Icon 2

---

iina/AboutWindowController.swift
iina/Base.lproj/AboutWindowController.xib
iina/Base.lproj/MainWindowController.xib
iina/Base.lproj/PlaylistViewController.xib
iina/Base.lproj/QuickSettingViewController.xib
iina/MPVController.swift
iina/MPVFilter.swift
iina/MPVTrack.swift
iina/MainWindowController.swift
iina/PlayerCore.swift
iina/PlaylistViewController.swift
iina/PrefKeyBindingViewController.swift
iina/QuickSettingViewController.swift
iina/Utility.swift
iina/ViewLayer.swift

---
A proper fix for both issues outlined above.  Please test it out, especially with long filenames and the fullscreen transition.
Caveats:
* This PR uses internal APIs. Essentially, `NSWindow` keeps changing the `NSTextField` for the title whenever switching between fullscreen and windowed mode. It also doesn't make the actual text field publicly available. Thus, the two solutions to accessing it are the API I used or iterating through `window.standardWindowButtons(.documentIcon).superview.subviews` for a `NSTextField`. Your choice on which one we use.
* I removed a line in `windowWillExitFullScreen` for reverting the appearance; I don't see what its purpose is. Please take a look to see if it's important.
* There is are fundamental issues with the layering of the views …

Add Document Icon Button, AutoLayout Quick Settings

---

iina/AppData.swift
iina/MPVController.swift
iina/MainWindowController.swift
iina/MainWindowMenuActions.swift
iina/MenuController.swift
iina/PlaybackInfo.swift
iina/PlayerCore.swift
iina/Regex.swift

`ontop`
- window's floating on top status should be syn ced with mpv's `ontop` property.
- able to set key bindings for `ontop` (e.g. `cycle ontop` `set ontop yes`).
- options like `ontop=yes` should work initially
`geometry`
- see [mpv's doc](https://mpv.io/manual/stable/#options-geometry) and test whether it works normally.
- make sure it doesn't break any existing function.

Connect more mpv window options

---

iina/Base.lproj/QuickSettingViewController.xib
iina/MainWindowController.swift
iina/PrefSubViewController.swift

* Fix a warning for printing an String?
* Remove unnecessary "-0-" constraints
* Xcode automatically sets allowsCharacterPickerTouchBarItem="YES" for text fields
---

Quick fixes for recently introduced regressions

---

iina/MainWindowController.swift

---
Hidden sidebar regardless its status to make sure it is hidden properly when switching between playlist and quick settings.

Fix sidebar overlapping when switching between playlist and quick settings

---

iina/MPVController.swift
iina/MainWindowController.swift

improve always on top behavior

---

iina/PlayerCore.swift

---
A quick bug fix, reported from telegram group: Videos with anamorphic (non-square) pixels would be played using SAR(Sample Aspect Ratio) on file load instead of DAR(Display Aspect Ratio).
I'm not able to always reproduce it: sometimes it stuck at SAR, sometimes it would jump from SAR to DAR. This commit let the program use DAR on file load.
Even with the commit, player would still use SAR on load for a moment, then resize to DAR size. Breakpoint on file load shows that mpv wouldn't report correct display width on the beginning. Maybe this commit fixes _nothing_. More tests are needed.

Use DAR on file load

---

iina/MPVController.swift
iina/VideoView.swift
iina/ViewLayer.swift

You have mistakes in handling thread synchronisation allowing OpenGL context to be destroyed in the middle of the draw procedure. As a result closing the window during video playback will cause crashes.
This change reworks the way uninitLock is used and eliminates the race condition.

Fixed at exit crashes during playback

---

iina/MainWindowController.swift

---
This pr fixes bugs reported from Cyrill@Telegram.
- Change the level of the ontop window. Now it is always under the inspector, etc.
- Keep level of full screen window `.normalWindow` to show settings panel properly.
- Assign `self.isOntop` new value after it is changed by the setting "Always float on top while playing".

Several changes on `ontop`

---

iina/SleepPreventer.swift

---
Revise lock as bool since `assertionID` will be overrided if the
`preventSleep` is called twice.

Attempt to fix 556

---

iina/AppDelegate.swift
iina/Info.plist

Accept dropped strings and URLs on IINA icon.
---
Idea by http://stackoverflow.com/questions/27420016/osx-drag-and-drop-text-not-file-to-app-dock-icon .
I used a quite 'dirty' way to prevent the open panel. I call a new method instead of `openFile(_:)` after 0.5s to judge if I have to open the panel. Because system call `applicationWillFinishLaunching(_:)` first. At that time, I have no idea about how to know whether the app opened by the accept dropping service or not.
This pull request also prevents the open panel from showing up when the app is called by the browser extension.

Accept dragged strings and URLs on icon, fix #294 (part 2), fix #374

---

iina/Base.lproj/Localizable.strings

---
I found a liitle typo in Localizable.strings(Base).

Fixed typo in Base Localizable.strings

---

iina/MainWindowController.swift

---
IINA was not redrawing the album cover on resize when playing audio files, There were a resize on launch so lower resolution cover gets directly stretched.
We assume that current render fps < 1 == playing audio file, and redraw on resize notif.

Redraw on audio file resize (cover display issue)

---

iina/MainWindowController.swift

---
This pull request refactors `hideUI()` and `showUI()` in MainWindowController. In principle, I made those two functions symmetrical.
```diff
fadeableViews.forEach { (v) in
-      v.alphaValue = 1
v.isHidden = false
}
```
`alphaValue` is managed by the animator. Change it manually is useless and somewhat invalid.
```diff
+    standardWindowButtons.forEach { $0.isEnabled = false }
```
Should be disabled.
```diff
-      self.animationState = .shown
+      // if no interrupt then hide animation
+      if self.animationState == .willShow {
+        self.animationState = .shown
+      }
```
Like `hideUI()`, `showUI()` should also be able to be interrupted by `hideUI()`.
```diff
-    if isMouseInWindow && animationState == .hidden {
+    if isMouseInWindow {
showUI()
``` …

Animation fix

---

iina/it.lproj/PrefGeneralViewController.strings

`Palylist:` should be `Playlist:`

Fix a typo in italian localization

---

iina/AppDelegate.swift
iina/Base.lproj/Localizable.strings
iina/Base.lproj/PrefKeyBindingViewController.xib
iina/MPVController.swift
iina/MainWindowController.swift
iina/MiniPlayerWindowController.swift
iina/PlaybackInfo.swift
iina/PlayerCore.swift
iina/PrefKeyBindingViewController.swift
iina/Preference.swift
iina/zh-Hans.lproj/Localizable.strings

---
This pull request integrates MediaPlayer framework and enables multiple system media controls. 
Even though the document says MediaPlayer framework is available on macOS 10.12.1+, based on by test, it only works on 10.13. So that I kept macOS 10.13- using the legacy mpv media key functionality and enables MediaPlayer framework on macOS 10.13+. The label `Use media keys` in Preferences > Keybindings will be displayed as `Use system media control` in macOS 10.13+.
It is supposed to
- make IINA stay in the touch bar "media center" system (#451)
- not capture keys(by mpv) anymore (i.e. the caps lock key) (#477, #846, #778)
- make IINA to be controlled by system (i.e. bluetooth devices, AirPods, media keys) (#799, #791)
- shows IINA in the "Now Playing" widget

MediaPlayer framework

---

browser/Open_In_IINA.safariextension/Info.plist
browser/Open_In_IINA.safariextension/global.js
browser/Open_In_IINA.safariextension/injected.js

---
This PR adds an “Open Link in IINA” item to context menus in Safari. It’s context-aware, so the item will only appear when the user is right-clicking on a link. This is useful because it allows the user to open linked content in IINA directly without having load the page first or copy the URL and paste it in IINA.

Add “Open Link in IINA” context menu item to Safari extension

---

iina/MainWindowController.swift
iina/TouchBarSupport.swift

---
This is purely an appearance change to make it consistent among the platform. When esc button is bound to exit full screen, the TouchBar ESC button should reflect it.

Change the esc button to exit-full-screen icon on the TouchBar.

---

iina.xcodeproj/project.pbxproj
iina/da.lproj/Localizable.strings
iina/de.lproj/Localizable.strings
iina/es.lproj/Localizable.strings
iina/fr.lproj/Localizable.strings
iina/it.lproj/Localizable.strings
iina/ja.lproj/Localizable.strings
iina/nl.lproj/Localizable.strings
iina/pl.lproj/Localizable.strings
iina/pt-BR.lproj/Localizable.strings
iina/ru.lproj/Localizable.strings
iina/sk.lproj/Localizable.strings
iina/tr.lproj/Localizable.strings
iina/uk.lproj/Localizable.strings
iina/zh-Hant.lproj/Localizable.strings
other/check_localizable.swift

Cocoa won't fallback to English localizations only for keys in `Localizable.string`; actually, build 68 already suffered from this problem due to my carelessness. Therefore I added an extra script to check missing keys in `Localizble.string` files while building.
Run `other/check_localizable.swift --fix` to fix them automatically.

Added a script to check Localizable.strings when building

---

iina/PlayerCore.swift
iina/ThumbnailCache.swift

---
Write video file's size and modified date to cache file. Check those properties to determine the video file remains the same.

Thumbnail cache

---

iina/PrefUIViewController.swift

---
When ```Initial window size``` was unchecked, the related controls weren't disabled on launch, because it was disabling the controls for ```Initial window position``` instead.

Properly disable Initial window size controls on launch

---

iina/MiniPlayerWindowController.swift

---
[PlayerCore.getMusicMetadata()](https://github.com/lhc70000/iina/blob/develop/iina/PlayerCore.swift#L1316-L1321) returns the tuple ```(title, album, artist)```, but the mini player assumed the order was ```(title, artist, album)```. This caused the mini player UI to display "Album - Artist" instead of "Artist - Album".

Fix order of artist and album in Music Mode

---

iina/PlayerCore.swift

---
Currently IINA does not switch to Music Mode if the audio file has multiple artwork images. With this change it checks that every video track is an artwork image.

Automatically switch to music mode when the file has multiple artwork images

---

iina/AppData.swift
iina/Utility.swift

- Log files were previously in: `~/Application Support/com.colliderli.iina/logs`
This made it impractical to use `Console.app` to view IINAs logs
- The change moves Log files to: `~/Library/Logs/com.colliderli.iina`
That allows `Console.app` to display IINAs logs live and is [standard macOS behaviour](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html)   
- Cache files were previously in: `~/Application Support/com.colliderli.iina/cache`
This impeded system maintainance and cache cleanup routines
- The change moves Cache files to: `~/Library/Caches/com.colliderli.iina`
That enables any system cleanup tools to remove IINAs cached files (e.g., thumbnails)

FEATURE: Use macOS' default Log/Cache directories

---

iina/OnlineSubtitle.swift
iina/OpenSubSubtitle.swift

---
Currently IINA only uses file hash to search on OpenSubtitle.org. This PR makes IINA search again using filename when the first attempt returns no result.
<s>Besides, this PR also fix a bug in the OpenSubtitle part. I'm not sure whether this bug exists for a long time or is due to OpenSubtitle's API change.</s> (Due to a temporary API change of opensubtitle)

Use filename to search on OpenSubtitle

---

iina/FFmpegController.m

---
`-[NSString fileSystemRepresentation]` better handles strange characters and is the recommended way of sending file paths to lower-level file APIs.

Use .fileSystemRepresentation when getting file paths from NSStrings.

---

iina/MainWindowController.swift

---
Quick fix for #1624, which has been bothering me as well. It seems that Interface Builder sets `refusesFirstResponder` to `true` by default, but the regular `NSButton` initializer doesn't.

Fix #1624 by having the OSC buttons refuse first responder

---

iina/Base.lproj/Localizable.strings
iina/OSDMessage.swift
iina/QuickSettingViewController.swift
iina/da.lproj/Localizable.strings
iina/de.lproj/Localizable.strings
iina/es.lproj/Localizable.strings
iina/fr.lproj/Localizable.strings
iina/it.lproj/Localizable.strings
iina/ja.lproj/Localizable.strings
iina/ko.lproj/Localizable.strings
iina/nl.lproj/Localizable.strings
iina/pl.lproj/Localizable.strings
iina/pt-BR.lproj/Localizable.strings
iina/ru.lproj/Localizable.strings
iina/sk.lproj/Localizable.strings
iina/tr.lproj/Localizable.strings
iina/uk.lproj/Localizable.strings
iina/zh-Hans.lproj/Localizable.strings
iina/zh-Hant.lproj/Localizable.strings

---
Add function to select None subtitle in menu; use "No subtitle loaded" and "No external subtitle found" instead of "\<None\>" when no suitable subtitle.
Before: <img width="524" alt="screen shot 2018-04-28 at 12 18 13" src="https://user-images.githubusercontent.com/2270433/39394750-51598328-4ade-11e8-8fa0-79c0ef3334a8.png">
After: ![image](https://user-images.githubusercontent.com/20237141/39412015-d77a062e-4bda-11e8-8ed6-6747a4ca183f.png)
Click "\<None\>" here now switch to \<None\>.
In case of there's no loaded subtitle and no external found:

Add function to select None subtitle in menu, fix #1653

---

iina/MiniPlayerWindowController.swift
iina/MiniPlayerWindowController.xib
iina/PlayerCore.swift

---
- Put the mute button in the mini player into slider popup and remove the numerical volume indicator
- Fix a bug where mute button does not update normally
- Enlarge the length of volume label (located in the slider popup) to ensure "1,000" can be fully displayed
- Bring VolumeSliderCell to miniplayer's volume slider
- Add haptic feedback support to miniplayer volume slider

Put the mute button in the mini player into slider popup, fix #1664

---

iina/MiniPlayerWindowController.swift

---
When changing the "Show remaining time" preference, the change is immediately visible in the OSC. However, after restarting IINA, Music Mode always shows the duration.

Respect "Show remaining time" preference in Music Mode

---

iina/MPVController.swift
iina/PlayerCore.swift

---
It seems that mpv retains the status of ab loop even when switching files in playlist or play next/prev. Added clearing ab loop when a new files is loaded.

Fix ab loop stays even when switching media files

---

iina/Base.lproj/MainWindowController.xib
iina/MainWindowController.swift
iina/MiniPlayerWindowController.swift
iina/MiniPlayerWindowController.xib
iina/TouchBarSupport.swift

---
I couldn't find a constant for the System Mini font size (9pt) for the mini player, so it's hardcoded.

Monospaced font for time labels in OSC and Touch Bar

---

iina/MainWindowController.swift

Previously, scroll wheel action was disabled in entire OSC. This pr enables scroll wheel to control volume only when the mouse is on volumeView (so does sliderView).

Override scrollwheel action when the cursor is hovering on volumeView or sliderView

---

iina/AppDelegate.swift
iina/DraggingDetect.swift
iina/HistoryWindowController.swift
iina/InitialWindowController.swift
iina/PlayerCore.swift
iina/PlaylistViewController.swift
iina/Utility.swift

- Make the original `openURL` private; every other public `openURL` must
call the new `open` method.
- Three public `openURL` methods:
- `openURLs`
- `openURL`
- `openURLString`
Make `openURLString` always calls `openURL`, `openURL` always calls `openURLs`
to ensure all public method calls must pass `openURLs`, hence we can
handle BD folders/playlist files correctly.
- Fix #1831 by resolving alias

Refactor on `PlayerCore.openURL(s)`

---

iina/MainWindowController.swift

All float views respect theme settings, but additionalInfoView all time light-gray. For example:
This PR fix that

Respect theme settings in additionalInfoView 

---

other/check_translation.swift

---
Modernize/potential bug fixes for check_translation:
Better range getter NSRegularExpressions: they expect NSRange, UTF-16 conted strings, but Swift Strings use a different counting method.

Fix counting of string types in check_translation.

---

iina/PlayerCore.swift

---
I don't believe this guard is needed (anymore?). The rest of the function works fine for URLs.

Automatically switch to Music Mode for audio URLs

---

iina/AppDelegate.swift

- this PR adds the `enqueue` query parameter for usage via IINAs URL Scheme
- the change has been discussed with @lhc70000
- this PR branches off the current work being done within #1935
- per default, `enqueue` is off (set to `0`) and does not change the IINA's familiar behavior of clearing the playlist upon opening an URL
- if `enqueue` is active (set to `1`), URLs supplied via the URL scheme will be added to the current playlist, with the playlist UI updating automatically.
- for the parameter to take effect, at least one existing playlist item is required
- the right `PlayerCore` instance is resolved via `PlayerCore.lastActive`, this has been proven to be stable and performant
- `iina://weblink?url=https://test.com/movie.mp4&enqueue=1`
- …

[URL Scheme] Support `enqueue` Query Parameter 

---

iina/FFmpegController.m

The current code in `FFmpegController.m` triggers undefined behavior with ogg-vorbis files which have embedded art-covers.
The problematic line can be found here:
https://github.com/lhc70000/iina/blob/e909cfdc406292c9ac57843a3dd77f1e60929a17/iina/FFmpegController.m#L122
If someone opens an ogg-vobis file which has an embedded covert-art, libavformat will set `avg_frame_rate` to zero by setting both the numerator and denominator to zero.
By looking at the definition of `av_q2d` we can see that it's a simple division and hence triggers undefine behaviour when both values are zero:
```c
static inline double av_q2d(AVRational a){
return a.num / (double) a.den;
}
```
This issue actually came up when I tried to open an ogg-vorbis file which had an embedded cover-art but iina crashed everytime. …

Fix a division by zero which is undefined behaviour

---

iina/PlaylistViewController.swift

---
- Currently, dragging / reordering any item within playlists loaded from YouTube result in the loss of all items' names , as they are reset to their internal `youtube-dl` id (e.g., `ytdl://PHov9j`), rendering the playlist unusable without warning.
- When dropping local media files onto a YouTube playlists, reordering the local items also results in the loss of all YouTube file titles.
- Playlist item names should remain intact, regardless of their source or of any dragging operation.
- This PR updates the logic for dragging/reordering items within playlists.
- By directly interfacing with MPVs native playlist sorting method (via `player.playlistMove`), the code is simplified, the internal playlist and UI are kept in sync, and items show their correct attributes.
- Multi-line drag & …

[BUGFIX] Fixes YouTube Playlist Item Dragging and Reordering

---

iina/MainWindowController.swift
iina/VideoView.swift

---
This PR would read current device ICC profile path and set `icc-profile` attribute in `mpv` to support correct color transformation.

Add support for auto select ICC profile

---

iina/MainWindowController.swift

Entering PiP and exiting fullscreen are orthogonal concepts; PiP manages its own window, so the two aren't mutually exclusive. Requesting one of them should not imply requesting the other. 
Whatever fullscreen / split-screen setup the user has should be preserved whenever possible — not torn down. For example, I might be watching something in fullscreen but need to do something else real quick. The natural way to do this is to activate PiP, move to another space and do the task, then use the Exit PiP button in the PiP window to _restore the setup to its previous state_.
Even worse is if I've put IINA in split-screen with another app to be able to watch a video without having a PiP window obscuring any part of the other app. If I want to complete a short task on another space, then I'm …

Don't exit fullscreen on entering PiP

---

iina/FileSize.swift

for example, the output of 1024 will be 1KB, not 1024B
---
1KB is better than 1000B.

improve FileSize.format() when size is unit size

---

iina/FFmpegController.m

Fix crash when pix_fmt is invalid value

---

iina/sv.lproj/PrefUIViewController.strings

Correct the mention of keys to map correctly to the mention of their respective functions
---
left / right was incorrectly translated to the equivalent of right / left

Minor adjustment of Swedish translation

---

iina/MPVFilter.swift

---
The filters we get from mpv have no explicit keys, they are "@0", "@1"
instead of "w", "h". So that when we get update of filters via
`getFilters`, our local copy of filters will become massy.

Add translation in MPVFilter's init

---

iina/PlaylistViewController.swift

Fix the issue metioned in #2207

Fix sometimes player cannot be determined and yield nil unwrap

---

iina/AppDelegate.swift
iina/Base.lproj/PrefUIViewController.xib
iina/MainWindowController.swift
iina/PrefUIViewController.swift
iina/Preference.swift
iina/ja.lproj/PrefUIViewController.strings

---
This PR will add ability to hide main window when entering Picture in Picture if window is not in fullscreen mode.
I looked in to it and I noticed that implementation is quite simple.
It doesn't require specification to re-show window when going back from PiP as PiP seems to be doing that already.
I also added option to enable/disable this behavior, but this may not needed. It depends on how you all thinks.

Hide main window when entering Picture in Picture

---

iina/Base.lproj/FilterWindowController.xib
iina/FilterWindowController.swift

---
Prevents crash when adding new custom MPV filter.  NewFilterSheet's add button is now disabled until the filter is given a name.
Changes to `NewFilterSheetViewController` (in `FilterWindowController.swift`):
1. new outlet "`addButton`"  in `NewFilterSheetViewController` that connects to `NewFilterSheet`'s add button
2. in `NewFilterSheetViewController.showSettings()`, check if quickInput is text field for name of custom filter and disable `addButton` if text field is empty
3. assign this `NSTextField's` delegate property to self
4. new extension to `NewFilterSheetViewController` in `FilterWindowController.swift` that implements `NSTexFieldDelegate: controlTextDidChange()` -- enables/disables add button if text/no-text
5. discarded all unintentional changes to` …

Prevent crash when adding mpv filter with no name

---

README.md

---
Homebrew maintainer here. [Options are no longer supported](https://brew.sh/2019/02/02/homebrew-2.0.0/) in the main [`homebrew-core`](https://github.com/Homebrew/homebrew-core) formulae repo.
Running the current command would give `Error: invalid option: --with-uchardet`. It is [already included in the formula](https://github.com/Homebrew/homebrew-core/blob/a506f8508e40d47040698349ba95d7df06f34d75/Formula/mpv.rb#L27).

README: update mpv install instructions (no flag)

---

iina/OpenURLWindowController.swift

If the URL input in the Open URL window contains a trailing newline the open operation fails. This is a common scenario e.g. when selecting (triple clicking) and copying an entire line that only consists of an URL.
For some reason the Open URL window does not funnel its open URL operation through `PlayerCore.openURLString` which would have been my first guess as to where URL strings centrally get converted into `URL`s. Anyway, this fixes the problem with trailing newlines at least in that window. 
I am not aware if there are any other ways to open a URL. If there's e.g. dragging and dropping which isn't in turn funneled through the Open URL window routines (unlikely) then there would most likely still be a problem. That's out of scope for this PR.

Trim URL string whitespace and newlines

---

iina/MPVController.swift
iina/MainWindowController.swift
iina/ViewLayer.swift

Fix stretched screen when entering and exiting fullscreen

---

README.md
other/change_lib_dependencies.rb

Fixes:
- `README.md` references `libmpv/include/mpv/` when in reality it’s `deps/include/mpv/`
- `README.md` doesn’t mention running pod install when you’re manually adding libraries
- `README.md` has some misc typos
- `other/change_lib_dependencies.rb` references the wrong Homebrew package in its help text
Workarounds:
- Homebrew’s mpv-iina package produces libmpv.1.*.0.dylib without +w which breaks the script `other/change_lib_dependencies.rb` (Homebrew’s mpv package does have +w on that .dylib file), added a step in `README.md` to fix that
---
I've tried building IINA using the instructions in README.md and ran into several issues. This PR updates the instructions to better reflect the actual steps needed to build the project from scratch. I also fixed a few …

Fixed build instructions in README.md, updated script help text

---

iina/Base.lproj/MiniPlayerWindowController.xib

---
7975166 makes slider knob clip through at the end of track. PlaySliderCell control size should be changed from small to regular to mitigate this.
Before:
After:

Fixes MiniPlayer slider knob getting out of bounds at the end of track

---

README.md

Convert headings into subheadings to a particular step in the described build process
---
The non-indented headings threw me off and made me skip steps that weren't intended to be skipped.

Fixed indentation in mpv build instructions

---

iina/Base.lproj/Localizable.strings

Replaced "to" with "by" in "Speed up/down to", since that is the correct term. 
If the menu item in question (Speed up to 1.5x) is clicked the two times, the term "to" incorrectly tells the users that the speed will still just be 1.5x. If however the term is "by" (Speed up by 1.5x), the user is correctly made aware that the current speed will by sped up 1.5x.

Corrected language

---

other/change_lib_dependencies.rb

Handle whitespace in path by surrounding it with double quotes
---
It's possible there's more than one place that need double quotes, I didn't check the whole document

Properly escape whitespace in change_lib_dependencies.rb

---

iina/Logger.swift

---
Currently, a log directory for 2020-12-29 is created for the current date (December 29, 2019), which is incorrect. Use yyyy instead of YYYY to get the actual calendar year (instead of the week-based year).

Fix logger date format

---

iina/QuickSettingViewController.swift

---
Trying to set subtitle border width in the quick settings gets it stuck at 1, this hooks it up to use the correct selected value.

Fix subtitle border width option in quick settings

---

iina/ThumbnailCache.swift

---
In 1.0.5, thumbnails will get generated for videos and saved to the disk cache, but they're not being read from the cache and get regenerated every time you open a video.
Reading the version as Int fixes checking the cache hit, since it was being read as the wrong integer size. It was also sized wrong when trying to read the images, messing up the alignment.

Fix thumbnail cache not being read

---

iina/AppDelegate.swift
iina/MainMenuActions.swift
iina/MainWindowController.swift
iina/MiniPlayerWindowController.swift
iina/PlaySliderCell.swift
iina/PlaybackInfo.swift
iina/PlayerCore.swift
iina/TouchBarSupport.swift

- Split `togglePause(_)` into `togglePause()`, `pause()` and `resume()`
- Provide `PlayerCore.info.isPlaying`, which is calcuated from isPaused

Pause resume refactor

---

iina/FileGroup.swift

---
This commit intends to fix a kind of infinite loops:
If there are files like:
/-test.mp4
|-dir0/a.sub
|-dir1/a.sub
|-dir2/a.sub
|-dir3/a.sub
The tryGroupFiles method would find it self infinitely looping i++ when dealing with these "a.sub" files. And the user may find iina using 100% CPU at this time.

Fix infinite loops

---

iina/AutoFileMatcher.swift

---
One subtitle will be used in`subAutoLoadOption.shouldLoadSubsMatchedByIINA()` and `subAutoLoadOption.shouldLoadSubsContainingVideoName()` at the same time.

Prevent subtitles from being matched twice. fix #2687

---

iina/SubChooseViewController.swift

Allows user to double-click on an online subtitle to download it immediately rather than having to select it then move the mouse to click the download button.

Double-click online subtitle to download it

---

iina/AppData.swift
iina/MPVController.swift
iina/MiniPlayerWindowController.swift
iina/PlayerCore.swift

Currently, if there's no video track, mpv won't send the `video reconfig` event and thus windows won't change their sizes accordingly. Info such as aspect ratio and video size will remain to be the last video track. I'm not sure whether it worked well before and it's an internal change in mpv. Now the player remains functional due to an awkward fallback mechanism, and here are some obvious glitches:
- Disable auto music mode switching and open an audio file without album art. The window aspect ratio will be the initial one (16:10) at first, but suddenly jump to 1:1 on resize. This also happens when switching back from music mode.
- Open a landscape or portrait video, switch to music mode, and open another audio without album art. The album art part of the mini player will …

Fix various issue regarding window size in music mode

---

iina/Base.lproj/Localizable.strings
iina/Base.lproj/MainWindowController.xib
iina/Base.lproj/MiniPlayerWindowController.xib
iina/DurationDisplayTextField.swift
iina/PlayerWindowController.swift
iina/Preference.swift
iina/TouchBarSupport.swift
iina/en.lproj/Localizable.strings

---
- Make the remaining time label in Touch Bar show total duration when touching on it (and vice versa.)
- Update its name and description in English
- `leftLabel` in the main window (and the mini player window) is now `DurationDisplayTextField` instead of `NSTextField`.

Make the remaining time label in Touch Bar show total duration when touching on it 

---

iina/en.lproj/PrefSubViewController.strings

The smallest commit I ever made most likely.
---
Fix a typo in the Subtitles tab in Preferences.

Fix typo in Subtitles Preferences

---

iina/HistoryWindowController.swift

---
This small PR fixes shortcuts in the `Playback History` window.
Currently it is not possible to focus the `Search` text field via `⌘ + F`.

Fixed shortcuts in HistoryWindowController.

---

iina/Base.lproj/QuickSettingViewController.xib

---
Constraints in the Video Quicksettings view were misconfigured. The "Aspect Ratio" section (and everything below it) had their vertical positioning constrained to the "Table View" instead of the table's respective "Scroll View". This means that if a video has more than 3 video tracks or so, Aspect ratio and everything below it are pushed down to be aligned with the bottom of the video track list, no matter how long that list is and even if everything after the third track is hidden by the limit of the scroll view.
This issue is understandably hard to come by since most media files only have 1 video track (if any, in case of audio only tracks). I happen to configure youtube-dl to show all tracks available giving me the ability to choose between them at runtime, …

Fix Video QuickSettings view

---

iina/PlayerCore.swift

Two systems were continuing to run when playback was paused.
The commit in the pull request:
- Changes `PlayerCore.pause` to invalidate the timer and stop the
display link thread
- Changes `PlayerCore.resume` to create the synchronization timer
and start the display link
---

Fix CPU is consumed when paused, #3537

---

iina/AboutWindowContributorAvatarItem.swift
iina/AboutWindowController.swift
iina/AssrtSubtitle.swift
iina/JustXMLRPC.swift
iina/OpenSubSubtitle.swift
iina/ShooterSubtitle.swift

This commit will eliminate Swift compiler build warnings due to backward
matching of unabled trailing closure being deprecated as of Swift 5.3.
The changes merely involve adding parameter labels to trailing closures in
calls to `Just.get` and `Just.post`.
- [x ] It implements / fixes issue #3466.
---

Fix unlabeled trailing closure build warnings, #3466

---

iina/Base.lproj/Contribution.rtf
iina/Info.plist
iina/ca.lproj/Contribution.rtf
iina/cs.lproj/Contribution.rtf
iina/da.lproj/Contribution.rtf
iina/de.lproj/Contribution.rtf
iina/en.lproj/Contribution.rtf
iina/es.lproj/Contribution.rtf
iina/fr.lproj/Contribution.rtf
iina/hi.lproj/Contribution.rtf
iina/it.lproj/Contribution.rtf
iina/ja.lproj/Contribution.rtf
iina/ko.lproj/Contribution.rtf
iina/nl.lproj/Contribution.rtf
iina/pl.lproj/Contribution.rtf
iina/pt-BR.lproj/Contribution.rtf
iina/ro.lproj/Contribution.rtf
iina/ru.lproj/Contribution.rtf
iina/sk.lproj/Contribution.rtf
iina/sv.lproj/Contribution.rtf
iina/tr.lproj/Contribution.rtf
iina/uk.lproj/Contribution.rtf
iina/zh-Hans.lproj/Contribution.rtf
iina/zh-Hant.lproj/Contribution.rtf

This commit will add the copyright to the app info window and update the
about window to display a copyright that reflects 2021 and uses the copyright
symbol.
- [ x] It implements / fixes issue #3470.
---

Fix app info missing copyright, #3470

---

iina/VideoView.swift

This commit will change the method `VideoView.updateDisplayLink` to
set the mpv property `override-display-fps` instead of the deprecated
property `display-fps`, eliminating a warning message logged by mpv.

Fix warning "display-fps" deprecated, #3464

---

iina/FFmpegController.m
iina/PlaylistViewController.swift

This commit will change the method PlaylistViewController.tableView to
check if PlayerCore.refreshCachedVideoInfo was able to populate
PlaybackInfo.cachedVideoDurationAndProgress and not submit a reload of
the view if the cache is missing data.
This commit also updates FFmpegController.probeVideoInfoForFile to log
errors when libavformat methods return an error code.
This fixes an infinite table view reload loop that currently occurs when
refreshCachedVideoInfo is unable to populate the cache.
The infinite reload loop may be the cause of this issue:
Excessive CPU consumption when opening the Playlist Panel, #3162
- [x ] It implements / fixes issue #3162.
---
This commit fixes a serious Playlist Panel issue.
Not certain it is the same problem reported in #3162.
See the …

Fix constant CPU usage by Playlist Panel, #3162

---

iina.xcodeproj/project.pbxproj
iina/AccessibilityPreference.swift
iina/AccessibilityPreferences.swift
iina/MainWindowController.swift

Added AccessiblityPreference struct containing methods that make it
easy for other code to handle the Reduce motion preference.
Modified methods in MainWindowController that support entering and
exiting full screen mode and showing and hiding the side bar to
suppress animations if Reduce motion has been enabled.
- [x ] It implements / fixes issue #3437.
---

Closes support Reduce motion preference, #3437

---

other/parse_doc.rb

This commit will change the script parse_doc.rb to treat the property
"current-tracks" as a special case and only add a comment to
MPVProperty that indicates why a constant wasn't generated for it.
- [ x] It implements / fixes issue #3494.
---

Fix script parse_doc.rb, MPVProperty fails to compile, #3494

---

iina/SleepPreventer.swift

This commit will change the method `SleepPreventer.preventSleep`
to submit a task to the main DispatchQueue to display an alert if macOS
returns an error when IINA asks it to not put the display to sleep.
This fixes a crash due to trying to display an alert using a thread other than
the main thread.
Logging has been added to log the failure macOS is returning.
- [x ] It implements / fixes issue #3478.
---
This also fixes issue #3361.

Fix IINA 1.2.0 crashes instantly (Big Sur), #3478

---

iina/Base.lproj/Contribution.rtf
iina/Info.plist
iina/ca.lproj/Contribution.rtf
iina/cs.lproj/Contribution.rtf
iina/da.lproj/Contribution.rtf
iina/de.lproj/Contribution.rtf
iina/en.lproj/Contribution.rtf
iina/es.lproj/Contribution.rtf
iina/fr.lproj/Contribution.rtf
iina/hi.lproj/Contribution.rtf
iina/it.lproj/Contribution.rtf
iina/ja.lproj/Contribution.rtf
iina/ko.lproj/Contribution.rtf
iina/nl.lproj/Contribution.rtf
iina/pl.lproj/Contribution.rtf
iina/pt-BR.lproj/Contribution.rtf
iina/ro.lproj/Contribution.rtf
iina/ru.lproj/Contribution.rtf
iina/sk.lproj/Contribution.rtf
iina/sv.lproj/Contribution.rtf
iina/tr.lproj/Contribution.rtf
iina/uk.lproj/Contribution.rtf
iina/zh-Hans.lproj/Contribution.rtf
iina/zh-Hant.lproj/Contribution.rtf
other/update_copyright.sh

The copyright year displayed in the about window and the macOS "Get Info"
window for the application should reflect the year in which the particular
release of the application was built.
Apparently from a legal perspective updating the copyright year is no longer
required. But users are used to the copyright matching up with the year of the
build and this does provide the user with useful information about the age of
the release. Therefore IINA should continue to update the copyright year.
- Update the copyright year to 2022
- Add a bash script "update_copyright.sh" to the other directory
---

Update copyright year to 2022

---

iina/MainWindowController.swift

Change MainWindowController.windowWillOpen to set the window's title to
"Window", the title a NSWindow has by default. If the title is not reset
when a window is reused then the wrong title will be displayed in the
"Window" menu.
- [x ] It implements / fixes issue #3159.
---

Fix currently open filenames not syncing, #3159

---

iina/PlayerWindowController.swift

Change PlayerWindowController.updatePlayTime to not report a fatal error
if the position or duration is not known as can occur when the function
is called while mpv is still loading the file.
- [ x] It implements / fixes issue #3013.
---

Fix fatal error, video info not available, #3013

---

iina/MPVController.swift
iina/VideoView.swift
iina/ViewLayer.swift

The commit in the pull request:
- Adds a context property to ViewLayer for the OpenGL context
- Changes MPVController.mpvInitRendering to save the OpenGL context
- Changes ViewLayer.draw to use the saved context
---

Fix pause the video and the program crashes, #3475

---

iina/VideoView.swift

The commmit will add a mouseUp method to the VideoView class that calls
MainWindowController.mouseUp. This is needed because adding a title to
the window after having removed it while in full screen mode causes AppKit
to stop calling the mouseUp method in the controller.
---
Reviewers should think about whether they would prefer I simplified the code and did not conditionalize it to not check for Big Sur and just always call the controller method.

Fix legacy fullscreen is broken (11.0.1), #3211

---

iina/Extensions.swift
iina/Info.plist
iina/MainWindowController.swift

The commit in the pull request:
- Extends NSScreen with a new optional computed property,
cameraHousingHeight
- Changes MainWindowController.legacyAnimateToFullscreen to check if
cameraHousingHeight indicates a camera housing intrudes into the
screen and if so reduces the size of the full screen video window's
view's frame appropriately.
---
This PR replaces PR #3559 and takes a different approach addressing code review comments in the original PR.

Fix camera housing blocks controller, #3558

---

iina/IINA.entitlements

This commit will replace the entitlement "com.apple.security.cs.allow-jit" with
"com.apple.security.cs.allow-unsigned-executable-memory" in the
IINA.entitlements file.
This is required because the OpenResty LuaJIT library is not following Apple's
best practices for JIT compilers that allow use of the more restrictive
entitlement. This has been reported in this LuaJIT issue:
Code Signature Invalid crash using com.apple.security.cs.allow-jit
https://github.com/openresty/luajit2/issues/145
---
See issue for full discussion.

Fix IINA crashes with 'Code Signature Invalid', #3551

---

iina/Base.lproj/Localizable.strings
iina/OSDMessage.swift
iina/PlayerCore.swift
iina/en.lproj/Localizable.strings

In addition to adding an OSD message for toggling file looping the
commit in the pull request also adds an OSD message for toggling
playlist looping. The text chosen for the OSD messages match up with
the names used in the menus, "File Loop" and "Playlist Loop". To
indicate the state of looping the new messages follow the convention of
other OSD messages and use a localized "On" or "Off". When file looping
is enabled the OSD will display:
File Loop: On
- Add a new enumeration case `fileLoop` to  `OSDMessage`
- Add a new enumeration case `playlistLoop` to  `OSDMessage`
- Update   `OSDMessage.message` to handle  `fileLoop`
- Update   `OSDMessage.message` to handle  `playlistLoop`
- Add text for `osd.file_loop` and `osd.playlist_loop` to base localized …

Close indicate on OSD when File Loop is toggled, #3229

---

iina/PlayerCore.swift

This commit will change the setting of PlaybackInfo.videoPosition in
PlayerCore.syncUI to take into account the value of the mpv eof-reached
property and adjust the position accordingly if the end of the video has been
reached.
- [ x] It implements / fixes issue #3331.
---

Fix  progress bar does not reach end #3331

---

iina/Extensions.swift
iina/MainWindowController.swift

- Add a new method selectDefaultScreen to MainWindowController that
selects the screen to use as the default for a window
- Add a new method logScreen to MainWindowController for screen
related log messages
- Change windowWillOpen to log information about screen selection
- Change windowWillOpen to use selectDefaultScreen
The new selectDefaultScreen method searches for a screen in this order:
- window!.screen: The screen where most of the window is on; it is
nil when the window is offscreen.
- NSScreen.main: The screen containing the window that is currently
receiving keyboard events.
- NSScreeen.screens[0]: The primary screen of the user’s system.
If the screen associated with the window is nil this method will fall
back to using the main screen. …

Fix crash on open when external display disconnected, #3695

---

.gitignore
iina/MPVController.swift
iina/MenuController.swift
iina/PlayerCore.swift

---
1. Store preference for playlist loop status
2. Make `loop file` actually work and add a `loop file` button
TODO: The style of the new `loop file` button in active mode doesn't
match other buttons in playlist view, which needs rework
Related PR: #3700

PlaylistView: Fix loop* issues

---

iina/Extensions.swift
iina/MainWindowController.swift

The commit updates MainWindowController to resize the window
appropriately when the screen the window is on changes if in legacy
full screen mode.
- Add a method setFrame to Extensions.NSScreen to set a window's
frame and content view frame to use the full screen
- Add call to setFrame in observer for
didChangeScreenParametersNotification
---

Fix window not resized when screen changes, #3715

---

iina/FilterWindowController.swift
iina/MPVController.swift
iina/MPVFilter.swift
iina/MainWindowMenuActions.swift
iina/MenuController.swift
iina/PlayerCore.swift
iina/SavedFilter.swift

- Add a new method removeFilter to MPVController that removes a filter
based on its position within the list of filters
- Add methods for removing audio and video filters based on their position
within the list of filters to PlayerCore
- Change FilterWindowController.removeFilterAction to use the new methods
- Add a parseRawParamString method to MPVFilter
- Add an isEqual method to MPVFilter
- Change  MPVFilter.init(rawString:) to properly handle filters with labels
- Add a debugDescription  property to  MPVFilter
- Change FilterWindowController.toggleSavedFilterAction to locate the saved
filter using MPVFilter objects instead of strings
- Change FilterWindowController.reloadTable to locate saved filters using
MPVFilter objects instead of strings
- Add a filtersAsString …

Fix audio filters cannot be removed, #3620

---

iina/MPVController.swift
iina/PlayerCore.swift

- Add code to MPVController.handlePropertyChange to suspend/resume
active systems not needed while paused
- Remove code added to PlayerCore methods pause and resume that
attempted to manage these active systems
This corrects a regression added by PR #3538 that could cause playback
to stutter, due to the display link not being restarted. The original
fix failed when the OSC was used to pause playback, which went through
PlayerCore.pause and then playback was resumed using the space bar which
by-passed PlayerCore.resume, leaving the display link shutdown.
---
This fixes a regression in the develop branch due to an incorrect fix.

Fix video stutters when resuming after pausing, #3752

---

iina/Base.lproj/InitialWindowController.xib
iina/InitialWindowController.swift

---
_[second attempt - prev PR got deleted when I renamed the branch]_
The Welcome window actually is displaying a button with the most recently played file, followed by a table of Recent File 2, Recent File 3, etc. The reason the up/down arrow keys caused a file to play was that the "selectionChanged" callback was being used as a proxy for detecting a user event.
I changed this so that:
- When window opens, we "pretend" the button with the most recent entry is selected, which makes sense because the table has no items selected. Thus, ENTER or RETURN at this point will open the most recent file, or if for some reason that is no longer available, tries to open the next most recent one.
- User can use UP and DOWN arrow keys to select recent files, which will highlight in …

Enable up/down & enter key in Welcome window (issue #3669)

---

iina/AppDelegate.swift
iina/Utility.swift
iina/iina-Bridging-Header.h

- Change AppDelegage.applicationWillFinishLaunching to log the IINA version,
FFmpeg version and the versions of FFmpeg libraries
- Change AppDelegage.applicationDidFinishLaunching to log the mpv version
The version of mpv is not logged in  applicationWillFinishLaunching because
mpv does not provide a static method that returns the version. To obtain
version related information you must construct a mpv object, which has side
effects. So the mpv version is logged in applicationDidFinishLaunching to
preserve the existing order of initialization.
- [x ] It implements / fixes issue #3490.
---

Closes log the versions of dependencies, #3490

---

iina/AutoFileMatcher.swift
iina/PlayerCore.swift

---
This change will:
- Add the `silent` parameter to `PlayerCore.addToPlaylist` to avoid calling `postNotification(.iinaPlaylistChanged)`
- Update `addFilesToPlaylist` in `AutoFileMatcher.swift` to use the silent parameter when batch calling `addToPlaylist`

Fix: add `silent` parameter to PlayerCore.addToPlaylist to avoid unnecessary playlistView refreshes in AutoFileMatcher.swift

---

iina/Base.lproj/MainWindowController.xib

The commit in the pull request will remove an extraneous and unneeded
action connection between the XIB and MainWindowController for the
additionalInfoTitle label.
---

Fix does not respond to additionalInfoTitle, #3811

---

iina/HistoryWindowController.swift

---
Looks like playback history searches are meant to be case-insensitive. But `String.lowercased()` was only called for one side of the comparison.

Fix bug: Playback History search returns no results for uppercase letters

---

iina/AppDelegate.swift

---
Since the "Enter Fullscreen" option already exists under the Video menu, this patch hides the instance under the Window menu, to conform with Apple HIG. Note:
- This change has no effect on the built-in `fn-F` shortcut, which still works.
- This is set as a preference value which MacOS recognizes, which means:
- Although it's set when IINA starts, it will not take effect until the app is closed & reopened.
- After being set, even old versions of IINA will hide the full-screen option in the Window menu (unless IINA's prefs are manually deleted or edited to remove this key)

Fix #3857: Enter Full Screen exists under 2 different menu items

---

iina/JavascriptAPIFile.swift

---
The current plugin file system read api is very slow, it takes ~8s to read 16MB file. The bottleneck is createUInt8Array which are copying in JavaScript.
In this PR we can directly use JavaScriptCore API JSObjectMakeTypedArrayWithBytesNoCopy to create type array directly in Swift, which is much faster
Test on Mac Studio (M1 Max), read 16 MB File to javascript
Before Change: 7338ms
After Change: 3.94 ms

Improve the file api performance for plugin system

---

iina.xcodeproj/project.pbxproj
iina/Lock.swift
iina/Logger.swift
iina/PrefAdvancedViewController.swift
iina/Utility.swift

- Add a new Lock class
- Change Logger to use a lock to coordinate closing of the log file
- Change Logger to not use `Utilities` methods that call back into the logger
- Change Logger to catch and handle exceptions thrown by file operations
- Remove logDirURL from Utilities
- Change PrefAdvancedViewController to use Logger.logDirectory instead of Utilities.logDirURL
These changes address multiple ways in which the logger can cause IINA to crash.
---
A new proposed fix for this issue that directly addresses the logger crash.

Fix NSFileHandleOperationException crash in logger, #3590

---

iina/PlayerCore.swift

The commit will add a guard statement to the updateInfo method in
NowPlayingInfoManager to check if mpv termination has been initiated.
---
There are multiple PRs outstanding with changes in this area, so likely I will need to rebase and correct merge conflicts when these are merged.

Fix crash in NowPlayingInfoManager during quit, #3607

---

iina/MainWindowController.swift
iina/VideoView.swift

We need to redraw a frame after entering PIP when pausing, and previously we perform such redraw in the next `layout`. However, it now takes two `layout`s before finishing entering PIP. This was tested on macOS 13 beta and macOS 12.6.
Changing the pending flag into a counter and redrawing twice solve the problem.

Fix white window after entering PIP when pausing

---

iina/AssrtSubtitle.swift
iina/Base.lproj/Localizable.strings
iina/Base.lproj/MainMenu.xib
iina/JustXMLRPC.swift
iina/MainMenuActions.swift
iina/OSDMessage.swift
iina/OnlineSubtitle.swift
iina/OpenSubSubtitle.swift
iina/ShooterSubtitle.swift
iina/Utility.swift

- Change OpenSubSubtitle.hash to throw noResult if the video is being streamed
- Change OpenSubSubtitle.requestIMDB to use the media title as the text for the lookup if the video is being streamed
- Change OpenSubSubtitle.hash and ShooterSubtitle.hash to ensure file is closed
- Improve logging when obtaining subtitles
- Change MainMenuActions.saveDownloadedSub to bring up a Save panel to ask the user where to save the downloaded subtitle file
- Change the "Save Downloaded Subtitle" menu item to end with an ellipsis to indicate the user will be prompted for additional information
- Change Utility.quickSavePanel to accept an optional filename parameter
- Add "Cannot connect" OSD message
- Add "Timed out" OSD message
- Change subtitle classes to use an extension when …

Fix subtitles won't show, any source, #3431

---

iina/AppData.swift
iina/AppDelegate.swift
iina/JavascriptAPIGlobal.swift
iina/MPVController.swift
iina/MainWindowController.swift
iina/MenuController.swift
iina/MiniPlayerWindowController.swift
iina/PlayerCore.swift

- Add isStopped and isShutdown properties to PlayerCore
- Rename PlayerCore property isMpvTerminated to isShuttingDown
- Add playbackStopped and mpvHasShutdown methods to PlayerCore
- Add savePlayerState method to PlayerCore
- Add iinaPlayerStopped and iinaPlayerShutdown notifications
- Change PlayerCore to post the new notifications
- Change savePlaybackPosition to not send a command to write the watch later file if playback has been stopped
- Move code in MainWindowController method windowWillClose related to stopping playback to the PlayerCore stop method
- Change MPVController to inform PlayerCore when the stop command finishes and when mpv shuts down
- Change MPVController to remove IINA preference observers before sending a quit command to mpv
- Change …

Fix random failure to resume playback position, #3939

---

iina/MainWindowController.swift
iina/PlaybackInfo.swift

The fix in PR #3434 MUST be merged before merging this commit..
- Change MainWindowController.hideUI to stop the timer that updates
the OSC
- Change MainWindowController.showUI to sync the UI and start the timer
- Change PlaybackInfo.constrainVideoPosition to check that`videoPosition
is not nil
---
See issue for details. Don't miss the above note about merging PR #3434 first!

Fix CPU is consumed by OSC while hidden, #3601

---

iina/PlayerCore.swift

The fix in the commit moves the resetting of the isStopped flag from the fileStarted method in PlayerCore to the fileLoaded method.
The method fileStarted was the wrong place to reset this flag because mpv will start loading the next file in the playlist while still stopping playback of the previous file.
---
This fixes a regression recently added to the develop branch.

Fix audio continues after window closed, #3995

---

iina/PlayerCore.swift

Steps to reproduce:
- Pause a video
- Enter Music Mode
- The time information is not available on the UI
Calling `syncUITime` when entering music mode solves the issue.

Fix a bug where music mode doesn't show time info

---

iina/AppData.swift
iina/Base.lproj/Localizable.strings
iina/Base.lproj/MainMenu.xib
iina/MainWindowController.swift
iina/MenuController.swift
iina/en.lproj/Localizable.strings
iina/en.lproj/MainMenu.strings

This commit will change these toggle menus to use "Hide" in their title instead of "Show" when selecting the menu item hides the panel:
- Show Chapters Panel
- Show Playlist Panel
- Show Quick Settings Panel
This commit adds text that will require localization.
This fix only corrects one part of the reported issue. The behavior of buttons still needs to be updated to adhere to the HIG.
---
This PR replaces the original PR, removing localization files.

Fix toggle menus to adhere to HIG, #3116

---

iina/MPVController.swift

This commit will change MPVController.mpvUninitRendering to lock and set the OpenGL context before calling the mpv render methods.
---

Fix quit triggers "invalid context state" error, #3593

---

iina/MainMenuActions.swift
iina/MainWindowMenuActions.swift
iina/MenuController.swift

- Move menuToggleVideoFilterString from MainWindowMenuActions
to MainMenuActionHandler
- Move menuToggleAudioFilterString from MainWindowMenuActions
to MainMenuActionHandler
- Change MenuController to call the methods in their new
location
---

Fix Saved Audio Filters disabled in music mode, #3818

---

iina/Base.lproj/MainWindowController.xib
iina/MainWindowController.swift
iina/PlaySliderCell.swift

- Change MainWindowController methods playSliderChanges and
updateTimeLabel to position the time preview relative to the progress
bar
- Add method canShowThumbnailAbove to MainWindowController
- Change updateTimeLabel to use canShowThumbnailAbove
- Change PlaySliderCell.awakeFromNib to set slider control size to small
for macOS 11+
- Increase bottom and top constraints around progress bar from 4.5 to 6
These changes stop the time preview from intruding into the progress bar
in the on screen controller.
---
Correct regression introduced by Big Sur.

Fix top of progress bar not behaving as such, #3911

---

iina/MPVController.swift
iina/MainWindowController.swift
iina/ViewLayer.swift

- Change VideoLaye.draw to queue a task to the mpvGLQueue queue
- Change MPVController.mpvUpdateCallback to call draw directly
- Change MainWindowController.enterInteractiveMode  to call draw directly
- Change mpvGLQueue to be a private constant
These changes cause all drawing to occur from tasks submitted to mpvGLQueue . Restricting all drawing to a single serial dispatch queue eliminates the data race with these two properties.
---

Fix TSan: data race ViewLayer.forceRender, #3827

---

iina/AppData.swift
iina/Extensions.swift
iina/KeyCodeHelper.swift
iina/KeyMapping.swift
iina/MenuController.swift
iina/PlayerCore.swift
iina/PrefKeyBindingViewController.swift

#3831 
#3881 
#3851
---
This patch is a subset of (and is actually back-ported from) #3847, and contains only the changes to parsing and mapping key bindings. It is the successor to #3833: it fixes a loophole in that logic which result in unused duplicate entries being stored, while also adding other fixes which couldn't be merged separately.
It does the following
- Splits `KeyMapping`'s `key` field into rawKey and `normalizedMpvKey`, similar to how its `action` field has raw & parsed version.
- Moves the existing mpv normalization logic out of the `KeyMapping` constructor and into `KeyCodeHelper`.
- Expands the mpv normalization logic to ensure that in normal form (fixes #3851):
- Special key symbols are capitalized
- A key's uppercase symbol is used if it is available, …

Multiple fixes to key binding parsing

---

iina/MainWindowController.swift

---
Looks like this slipped through the cracks somehow.

Fix: PlayerWindowController.windowDidChangeScreen not getting called (issue 4025)

---

iina/MainWindowController.swift

This workaround also addresses another macOS Ventura regression where an external monitor goes black, #4015.
This same dimming problem was reported in issues #3880, #4013 and #4014.
The workaround changes the windowDidLoad method of MainWindowController such that when running under macOS Ventura it will add a tiny subview with such a low alpha level it is invisible to the human eye.
Issue #4015 has been reproduced without IINA, so we are certain this is a regression in macOS 13. At this time we do not know the root cause and can not explain why this workaround works.
---
Starting with macOS 13, some strange behavior can be seen when viewing videos in full screen in HDR mode. The screen will be dimmed when the player controls disappear. This workaround adds a tiny …

Workaround for dimmed HDR content in full screen on macOS 13, #3844

---

iina/AppDelegate.swift

---
Adds a simple check to avoid a fatal error at startup, if a single dash (`-`) is included in the args.
It was easy to confirm the crash, and also confirm the fix, by just supplying an arg in XCode's Scheme Editor:

Fix crash when single dash ("-") arg is supplied to IINA via cmd line

---

iina/InitialWindowController.swift

---
The last played file is checked against the recent files list so that it doesn't appear twice, but if one is a symlink, it can give a false negative and result in a duplicate listing. This seems to be a bigger problem for files in /tmp and /var, which Apple now links to /private/tmp and /private/var, so they can have different paths depending on which MacOS API they came from.
This fix adds `resolvingSymlinksInPath()` to both sides of the comparison, which is needed to normalize both paths. Apple treats /var and /tmp a bit strangely. See [this discussion](https://stackoverflow.com/questions/43031045/for-what-paths-is-resolvingsymlinksinpath-wrong).

Resolve symlinks when comparing recent files against last played file
