iina/iina

- iina/MainWindowController.swift
- iina/PlayerCore.swift
Revised PR according to the owner's comments.
> fixed width changes when moving slider in touchbar

- CONTRIBUTING.md
- README.md
This improved the grammars and structures in README.md and CONTRIBUTING.md to make it easier to understand
> Improved README.md and CONTRIBUTING.md

- iina/MainWindowController.swift
- iina/PlayerCore.swift
- iina/VideoView.swift
~~Still need to deal with mouse tracking.~~
> High power consumption after closing main window

- README.md
- other/change_lib_dependencies.rb
* It's fully automated. No manual command is required.
* No need to run with sudo.
> rewrite change_lib_dependencies.rb

- iina.xcodeproj/xcshareddata/xcschemes/iina.xcscheme
This is needed for almost every CI to work.
> Share scheme for CI

- iina/AppData.swift
- iina/InspectorWindowController.swift
- iina/MPVChapter.swift
- iina/MPVController.swift
- iina/MainWindowController.swift
- iina/PlayerCore.swift
- iina/VideoTime.swift
> Store seconds as Double type in VideoTime and increase progress bar refresh rate.

- iina.xcodeproj/project.pbxproj
- iina/Base.lproj/PrefGeneralViewController.xib
- iina/MPVController.swift
- iina/PlayerCore.swift
- iina/Preference.swift
- iina/zh-Hans.lproj/PrefGeneralViewController.strings
...with a new default-on option to control the behavior
> Correctly handle EOF event on last media in playlist

- iina.xcodeproj/project.pbxproj
- iina/Base.lproj/MainWindowController.xib
- iina/MainWindowController.swift
- iina/Utility.swift
This should have been part of #111.
> Update MainWindowController.xib to support Force Touch

- iina/AppDelegate.swift
- iina/Base.lproj/PrefGeneralViewController.xib
- iina/Preference.swift
- iina/zh-Hans.lproj/PrefGeneralViewController.strings
Default macOS app have an init open window. Some users don't know how to open files without the init open window.
> Add an init open window when finsh starting. Fix #13, #101.

- iina/de.lproj/PrefSubViewController.strings
Added missing string for "Download subtitles from:" ( seems that I overlooked it )
Thank you @inflation #261
> German Translation: Added missing string

- iina/ko.lproj/Localizable.strings
- iina/ko.lproj/QuickSettingViewController.strings
found mistranslated word and fix it.
> fix a few mistranslations.

- iina/de.lproj/Localizable.strings
- iina/de.lproj/MainMenu.strings
- iina/de.lproj/PrefCodecViewController.strings
- iina/de.lproj/PrefSubViewController.strings
- iina/de.lproj/PrefUIViewController.strings
> [GERMAN] Added missing translations

- iina/MainWindowController.swift
---
Revert some lines of code in 06d6d9b to prevent crash in 10.12.4 beta.
> Fix crash in macOS 10.12.4 beta(16E144f).

- iina/Base.lproj/MainWindowController.xib
- iina/MPVController.swift
- iina/MainWindowController.swift
---
- Fix space key not working.
- Fix some minor UI problem related to window sizing.
Special thanks to @beretboat!
> Fix space key

- ISSUE_TEMPLATE.md
---
I have no idea about how to write pull request message to follow the template because it's such a little fix.
> Fix typo in ISSUE_TEMPLATE.md

- iina.xcodeproj/project.pbxproj
- iina/MainWindowController.swift
- iina/MainWindowMenuActions.swift
- iina/MenuController.swift
- iina/iina-Bridging-Header.h
---
Adds a check for macOS Sierra before trying to enable Picture in Picture.
> Bugfixes for Picture in Picture

- iina.xcodeproj/project.pbxproj
- iina/AppData.swift
- iina/Base.lproj/KeyBinding.strings
- iina/Base.lproj/KeyRecordViewController.xib
- iina/Extensions.swift
- iina/KeyBindingCriterion.swift
- iina/KeyBindingDataLoader.swift
- iina/KeyBindingItem.swift
- iina/KeyBindingTranslator.swift
- iina/KeyRecordViewController.swift
- iina/Utility.swift
- iina/en.lproj/KeyBinding.strings
- iina/zh-Hans.lproj/KeyBinding.strings
---
An easier way to add key bindings.
> Refine key bindings

- iina/AppData.swift
- iina/Base.lproj/InspectorWindowController.xib
- iina/FileSize.swift
- iina/InspectorWindowController.swift
- iina/PlayerCore.swift
- iina/Preference.swift
> The new inspector

- iina/ko.lproj/InspectorWindowController.strings
- iina/ko.lproj/KeyBinding.strings
- iina/ko.lproj/Localizable.strings
- iina/ko.lproj/MainMenu.strings
- iina/ko.lproj/PrefControlViewController.strings
- iina/ko.lproj/PrefGeneralViewController.strings
- iina/ko.lproj/PrefNetworkViewController.strings
- iina/ko.lproj/PrefSubViewController.strings
> Korean Translation: translate added features

- iina.xcodeproj/project.pbxproj
- iina/ko.lproj/Contribution.rtf
- iina/ko.lproj/InfoPlist.strings
---
**Description:*
Korean Translation: add contributor list to about window
Korean Translation: misc change in contribution.rtf, infoPlist.strings
> Korean Translation: add contributor list to about window

- iina/PlayerCore.swift
> Fix Issue #426

- iina/Base.lproj/MainWindowController.xib
Change the default value of left and right labels and the initial value
for progress bar.
---
The default value of left and right labels are "-:--".
> Fix #471, placeholder issue

- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
- README.md
---
This should reduce issue duplication and non-English reports.
> Improve issue template

- Podfile
- Podfile.lock
- iina.xcodeproj/project.pbxproj
- iina/Base.lproj/KeyRecordViewController.xib
- iina/Base.lproj/PrefKeyBindingViewController.xib
- iina/Extensions.swift
- iina/KeyBindingItem.swift
- iina/KeyBindingTranslator.swift
- iina/KeyCodeHelper.swift
- iina/KeyMapping.swift
- iina/KeyRecordViewController.swift
- iina/MPVCommandFormat.strings
- iina/PrefKeyBindingViewController.swift
- iina/config/iina-default-input.conf
- iina/en.lproj/KeyBinding.strings
- iina/en.lproj/Localizable.strings
- iina/zh-Hans.lproj/KeyBinding.strings
- iina/zh-Hans.lproj/KeyRecordViewController.strings
- iina/zh-Hans.lproj/Localizable.strings
- iina/zh-Hans.lproj/PrefAdvancedViewController.strings
- iina/zh-Hans.lproj/PrefKeyBindingViewController.strings
> More readable keybindings

- .gitignore
- iina.xcodeproj/project.pbxproj
- iina/Base.lproj/Localizable.strings
- iina/Extensions.swift
- iina/FilterWindowController.swift
- iina/MPVController.swift
- iina/MainWindowMenuActions.swift
- iina/OnlineSubtitle.swift
- iina/PlayerCore.swift
- iina/PlaylistViewController.swift
- iina/PrefAdvancedViewController.swift
- iina/PrefKeyBindingViewController.swift
- iina/PrefSubViewController.swift
- iina/ScriptLoader.swift
- iina/SleepPreventer.swift
- iina/Utility.swift
- iina/VideoView.swift
> Replace showAlert() with loclaized one.

- iina.xcodeproj/project.pbxproj
- iina/it.lproj/Contribution.rtf
- iina/it.lproj/KeyBinding.strings
- iina/it.lproj/Localizable.strings
- iina/it.lproj/SubSelectWindowController.strings
> Update Italian translation

- iina/Base.lproj/QuickSettingViewController.xib
- iina/QuickSettingViewController.swift
> Synchronize QuickSettingsView text fields and slider and localize, fix #425, #492

- iina.xcodeproj/project.pbxproj
- iina/fr.lproj/AboutWindowController.strings
- iina/fr.lproj/Contribution.rtf
- iina/fr.lproj/InspectorWindowController.strings
- iina/fr.lproj/KeyBinding.strings
- iina/fr.lproj/KeyRecordViewController.strings
- iina/fr.lproj/Localizable.strings
- iina/fr.lproj/MainMenu.strings
- iina/fr.lproj/MainWindowController.strings
- iina/fr.lproj/PrefAdvancedViewController.strings
- iina/fr.lproj/PrefCodecViewController.strings
- iina/fr.lproj/PrefControlViewController.strings
- iina/fr.lproj/PrefKeyBindingViewController.strings
- iina/fr.lproj/PrefNetworkViewController.strings
- iina/fr.lproj/PrefSubViewController.strings
- iina/fr.lproj/PrefUIViewController.strings
- iina/fr.lproj/QuickSettingViewController.strings
---
Added new french translations
> French: added new translations

- iina.xcodeproj/project.pbxproj
- iina/AppDelegate.swift
- iina/Base.lproj/Localizable.strings
- iina/Base.lproj/OpenURLAccessoryViewController.xib
- iina/Extensions.swift
- iina/OpenURLAccessoryViewController.swift
- iina/PlayerCore.swift
- iina/Preference.swift
- iina/zh-Hans.lproj/OpenURLAccessoryViewController.strings
- Add GUI for HTTP authentication.
- Add links to browser extensions.
- Better handles user's input.
> Improve "open url" dialog

- iina.xcodeproj/project.pbxproj
- iina/ko.lproj/Localizable.strings
- iina/ko.lproj/OpenURLAccessoryViewController.strings
---
Korean Translation: localize open-url-dialog
> Korean Translation: localize open-url-dialog

- iina.xcodeproj/project.pbxproj
- iina/AppData.swift
- iina/Base.lproj/InfoPlist.strings
- iina/Base.lproj/MainWindowController.xib
- iina/Extensions.swift
- iina/MPVController.swift
- iina/MainWindowController.swift
- iina/MainWindowMenuActions.swift
- iina/OSDMessage.swift
- iina/OnlineSubtitle.swift
- iina/PlaybackInfo.swift
- iina/VideoTime.swift
- Add optional progress bar or detail text for OSD
- Add more OSD types, partly fix #490
> Improve osd

- iina/Base.lproj/PrefGeneralViewController.xib
- iina/MainWindowController.swift
- iina/Preference.swift
- iina/zh-Hans.lproj/PrefGeneralViewController.strings
---
Black out other screens in fullscreen. Did not test under macOS 10.11 or below, but I think I did not use any incompatible API.
> Add an option to black out other screens in fullscreen mode

- iina/Base.lproj/PrefSubViewController.xib
---
There exists a layout issue when the scrollbars are always enabled. The details are explained in #588 and #486. The changes include:
* Eliminated constraint warnings.
* Hidden horizontal scrollbar.
* Added constraint for a vertical scrollbar.
> Update scrollbar layout in subtitle preferences

- iina.xcodeproj/project.pbxproj
- iina/fr.lproj/KeyBinding.strings
- iina/fr.lproj/MainMenu.strings
- iina/fr.lproj/MainWindowController.strings
- iina/fr.lproj/OpenURLAccessoryViewController.strings
- iina/fr.lproj/PrefGeneralViewController.strings
- iina/fr.lproj/PrefKeyBindingViewController.strings
- iina/fr.lproj/PrefUIViewController.strings
- iina/fr.lproj/SubSelectWindowController.strings
---
French translation for new features.
> updated french translation

- iina/MainWindowController.swift
> Fixed OSCPosition switching.

- iina.xcodeproj/project.pbxproj
- iina/it.lproj/HistoryWindowController.strings
- iina/it.lproj/InfoPlist.strings
- iina/it.lproj/InspectorWindowController.strings
- iina/it.lproj/KeyBinding.strings
- iina/it.lproj/Localizable.strings
- iina/it.lproj/MainMenu.strings
- iina/it.lproj/OpenURLAccessoryViewController.strings
- iina/it.lproj/PrefControlViewController.strings
- iina/it.lproj/PrefGeneralViewController.strings
- iina/it.lproj/PrefKeyBindingViewController.strings
- iina/it.lproj/PrefNetworkViewController.strings
- iina/it.lproj/PrefSubViewController.strings
> Italian translation (recreate #625)

- iina/Extensions.swift
- iina/FileGroup.swift
- iina/PlaybackInfo.swift
- iina/PlayerCore.swift
- iina/PlaylistViewController.swift
- iina/QuickSettingViewController.swift
- iina/Utility.swift
Improved auto loading and subtitle matching algorithm. Includes updates after @saagarjha's review on last PR.
> Auto load 2

- iina/it.lproj/KeyBinding.strings
- iina/it.lproj/Localizable.strings
- iina/it.lproj/PlaylistViewController.strings
- iina/it.lproj/PrefSubViewController.strings
- iina/it.lproj/QuickSettingViewController.strings
Added translation of last strings about subtiltes
> [it] Added last strings

- iina/MainWindowTouchBarSupport.swift
> Make touchbar slider looks more like the Quicktime's one

- iina/AppDelegate.swift
- iina/FileGroup.swift
- iina/Info.plist
- iina/MPVController.swift
- iina/PlaybackInfo.swift
- iina/PlayerCore.swift
- iina/PlaylistViewController.swift
- Fixed several crashes introduced by auto load feature
- Improved thread safety
- Improved precision
> Auto load 3

- iina/Base.lproj/Localizable.strings
- iina/Base.lproj/PrefCodecViewController.xib
- iina/MPVController.swift
- iina/PlayerCore.swift
- iina/PrefCodecViewController.swift
- iina/Preference.swift
- iina/zh-Hans.lproj/Localizable.strings
- iina/zh-Hans.lproj/PrefCodecViewController.strings
- Add HwDec `auto-copy` option.
- Ask user to switch to `auto-copy` or `no` before applying video filters.
> Better compatibility for video filters and hardware decoding

- iina.xcodeproj/project.pbxproj
- iina/fr.lproj/HistoryWindowController.strings
- iina/fr.lproj/Localizable.strings
- iina/fr.lproj/MainMenu.strings
- iina/fr.lproj/MainWindowController.strings
- iina/fr.lproj/PlaylistViewController.strings
- iina/fr.lproj/PrefCodecViewController.strings
- iina/fr.lproj/PrefGeneralViewController.strings
- iina/fr.lproj/PrefSubViewController.strings
- iina/fr.lproj/QuickSettingViewController.strings
---
I'm sorry for the delay, I've been busy lately. In this MR, I've updated the french translation, adding all the missing strings. `swift other/check_translation.swift fr` now says "Finished. Issues count: fr 0".
Nice script by the way :-)
> french translation: added missing strings

- iina/PlayerCore.swift
- iina/PlaylistViewController.swift
- iina/Utility.swift
- iina/VideoView.swift
---
This pr adapts playlist code for multi window
> Fix playlist drag and drop

- iina/PlaySliderCell.swift
---
Change play slider bar radius to 1.5
> Change play slider bar radius to 1.5.

- iina/PlaylistViewController.swift
---
Added option to add multiple files to playlist
> Added option to add multiple files to playlist

- iina/FFmpegController.m
- iina/MainWindowController.swift
- iina/MainWindowTouchBarSupport.swift
- iina/PlayerCore.swift
- iina/ThumbnailCache.swift
This PR fixed all known problem for touch bar slider, and adjusted its appearance.
> Thumbnail peek fix

- iina.xcodeproj/project.pbxproj
- iina/it.lproj/HistoryWindowController.strings
- iina/it.lproj/InitialWindowController.strings
- iina/it.lproj/KeyBinding.strings
- iina/it.lproj/Localizable.strings
- iina/it.lproj/MainMenu.strings
- iina/it.lproj/PrefCodecViewController.strings
- iina/it.lproj/PrefGeneralViewController.strings
- iina/it.lproj/PrefUIViewController.strings
Italian update translation for 0.0.12 release with fixed 2 errors form check translation script.
> Italian translation for 0.0.12 (#826)

- iina.xcodeproj/project.pbxproj
- iina/fr.lproj/HistoryWindowController.strings
- iina/fr.lproj/InitialWindowController.strings
- iina/fr.lproj/Localizable.strings
- iina/fr.lproj/MainMenu.strings
- iina/fr.lproj/PrefGeneralViewController.strings
- iina/fr.lproj/PrefSubViewController.strings
- iina/fr.lproj/PrefUIViewController.strings
---
I also added the missing strings from the previous MR (in Localizable.strings)
> [french] added new strings for 0.0.12

- iina/de.lproj/Localizable.strings
Added translation of alert.filter_hwdec.message
> Translation of alert.filter_hwdec.message

- iina/ja.lproj/HistoryWindowController.strings
- iina/ja.lproj/InitialWindowController.strings
- iina/ja.lproj/Localizable.strings
- iina/ja.lproj/MainMenu.strings
- iina/ja.lproj/MainWindowController.strings
- iina/ja.lproj/PlaylistViewController.strings
- iina/ja.lproj/PrefCodecViewController.strings
- iina/ja.lproj/PrefGeneralViewController.strings
- iina/ja.lproj/PrefSubViewController.strings
- iina/ja.lproj/PrefUIViewController.strings
> [Japanese] added new strings for 0.0.12

- iina.xcodeproj/project.pbxproj
- iina/Assets.xcassets/nextl.imageset/Contents.json
- iina/Assets.xcassets/nextl.imageset/next.pdf
- iina/Assets.xcassets/nextr.imageset/Contents.json
- iina/Assets.xcassets/nextr.imageset/nextr.pdf
- iina/Base.lproj/MainMenu.xib
- iina/Base.lproj/MainWindowController.xib
- iina/Base.lproj/PrefUIViewController.xib
- iina/MPVTrack.swift
- iina/MainMenuActions.swift
- iina/MainWindowController.swift
- iina/MainWindowMenuActions.swift
- iina/MenuController.swift
- iina/MiniPlayerWindowController.swift
- iina/MiniPlayerWindowController.xib
- iina/MiniPlayerWindowMenuActions.swift
- iina/PlaybackInfo.swift
- iina/PlayerCore.swift
- iina/Preference.swift
- iina/QuickSettingViewController.swift
- iina/Utility.swift
- iina/zh-Hans.lproj/MainMenu.strings
- iina/zh-Hans.lproj/PrefUIViewController.strings
Although IINA is not designed to be a music player, it seems that quite a lot user are using it to play audio files. In previous versions it only shows an awkward black window most of the times. This PR aims to solve such problem by adding a "music mode" like the mini player in iTunes, with a configurable option to switch to this mode automatically when a media contains no video track or album cover only.
It also contains a refactor on the menu system. A new class `MainMenuActionsHandler` was added for handling general menu actions and will be inserted into the responder chains of `MainWindowController` and `MiniPlayerWindowController` at runtime.
> Music mode / Mini Player

- iina/AppData.swift
- iina/Extensions.swift
- iina/MPVController.swift
- iina/MainWindowController.swift
- iina/MainWindowMenuActions.swift
- iina/PlayerCore.swift
#822 
Also contains some other refactors.
> Bridge window scale

- iina/MainWindowController.swift
> Xjbeta 811

- iina/MainWindowController.swift
> Screen related fix

- iina/Base.lproj/InspectorWindowController.xib
The author of iina? No, not yet. The author of the patch!? That's me :)
https://github.com/lhc70000/iina/issues/1244
---
Allow info window to be resized vertically by converting two constraints from == to >=.
> Allow info window to be resized vertically

- iina-cli/main.swift
- iina.xcodeproj/project.pbxproj
- iina/Base.lproj/FilterPresets.strings
- iina/Base.lproj/FilterWindowController.xib
- iina/Base.lproj/Localizable.strings
- iina/Base.lproj/MainMenu.xib
- iina/CropSettingsViewController.swift
- iina/DraggingDetect.swift
- iina/FilterPresets.swift
- iina/FilterWindowController.swift
- iina/FreeSelectingViewController.swift
- iina/KeyCodeHelper.swift
- iina/KeyRecordView.swift
- iina/KeyRecordViewController.swift
- iina/MainWindowMenuActions.swift
- iina/MenuController.swift
- iina/OSDMessage.swift
- iina/PlayerCore.swift
- iina/Preference.swift
- iina/SavedFilter.swift
- iina/Utility.swift
- Users can now save an added filter, and assign a shortcut key to it.
- Support dragging a 3D LUT file (3dl, cube, dat or m3d) to main window to apply it directly.
> Save filters & enhancement for 3D LUT files

- iina/da.lproj/Contribution.rtf
---
Updated contribution.rtf to Danish
> Updated Danish translations

- iina/MainWindowController.swift
Fullscreen should be disabled in music mode.
---
By preventing IINA from _entering_ fullscreen in music mode.
> Disable fullscreen in music mode

- iina/InitialWindowController.swift
> use Utility to get version.

- iina/ko.lproj/Localizable.strings
- iina/ko.lproj/PrefGeneralViewController.strings
---
Korean Translation: update translation for build 67
- beta-channel
- add localization for touch bar remaining time
> Korean Translation: update translation for build 67

- iina.xcodeproj/project.pbxproj
- iina/ko.lproj/InitialWindowController.strings
- iina/ko.lproj/Localizable.strings
- iina/ko.lproj/PrefOSCToolbarSettingsSheetController.strings
- iina/ko.lproj/PrefSubViewController.strings
- iina/ko.lproj/PrefUIViewController.strings
update localization for beta-release.
update localization for responsive-osc
---
> Korean Translation: update localization for beta-release, responsive-osc

- iina.xcodeproj/project.pbxproj
- iina/ko.lproj/Localizable.strings
- iina/ko.lproj/MainMenu.strings
- iina/ko.lproj/PlaylistViewController.strings
- iina/ko.lproj/SubChooseViewController.strings
---
Korean Translation:
- localize support adding URL to playlist feature
- refine minor translations.
- Add korean localization for SubChooseViewController
> Korean Translation: localize SubChooseViewController, adding URL to playlist feature

- iina/MPVController.swift
- iina/PlayerCore.swift
- iina/ViewLayer.swift
---
Dispatch queue with proper QoS
> Dispatch queue with proper QoS

- iina/AutoFileMatcher.swift
- iina/CropBoxView.swift
- iina/CropBoxViewController.swift
- iina/Extensions.swift
- iina/FileGroup.swift
- iina/FilterPresets.swift
- iina/FilterWindowController.swift
- iina/InitialWindowController.swift
- iina/InspectorWindowController.swift
- iina/JustExtension.swift
- iina/KeyBindingTranslator.swift
- iina/MPVFilter.swift
- iina/MPVTrack.swift
- iina/MainWindowController.swift
- iina/MenuController.swift
- iina/OSDMessage.swift
- iina/PlayerCore.swift
- iina/PlaylistViewController.swift
- iina/PrefKeyBindingViewController.swift
- iina/PrefSubViewController.swift
- iina/QuickSettingViewController.swift
- iina/VolumeSliderCell.swift
---
Just a bunch of various changes to modernize Extensions.swift.
> Clean up extensions

- iina/AutoFileMatcher.swift
- iina/PlayerCore.swift
- iina/Preference.swift
Due to there will be a UI change in Preferences panel, no GUI work in this PR.
> Search subtitles online automatically (#639)

- iina-cli/main.swift
---
The piping capability was only described but the actual arguments where not shown. I only found out about this by looking at the code.
> Add argument for stdin piping to iina-cli help

- iina.xcodeproj/project.pbxproj
- iina/AppDelegate.swift
- iina/AssrtSubtitle.swift
- iina/AutoFileMatcher.swift
- iina/FileGroup.swift
- iina/HistoryController.swift
- iina/JustXMLRPC.swift
- iina/KeyCodeHelper.swift
- iina/KeyMapping.swift
- iina/Logger.swift
- iina/MPVController.swift
- iina/MPVFilter.swift
- iina/MainMenuActions.swift
- iina/MainWindowController.swift
- iina/MenuController.swift
- iina/MiniPlayerWindowController.swift
- iina/OnlineSubtitle.swift
- iina/OpenSubSubtitle.swift
- iina/PlayerCore.swift
- iina/PrefKeyBindingViewController.swift
- iina/PrefSubViewController.swift
- iina/Preference.swift
- iina/SleepPreventer.swift
- iina/ThumbnailCache.swift
- iina/Utility.swift
- iina/ViewLayer.swift
This implements #1541.
And will help debugging #1724 (#1641 #1235 #1662 #1722) if it's still not solved in beta2.
As said in #1691,
> Having a Utility type is an anti-pattern.
So this PR is also the first step to separate `Utility` into small components.
> Logging system

- iina.xcodeproj/xcshareddata/xcschemes/iina.xcscheme
- iina/AppDelegate.swift
- iina/AssrtSubtitle.swift
- iina/AutoFileMatcher.swift
- iina/FileGroup.swift
- iina/HistoryController.swift
- iina/JustXMLRPC.swift
- iina/KeyCodeHelper.swift
- iina/KeyMapping.swift
- iina/Logger.swift
- iina/MPVController.swift
- iina/MainMenuActions.swift
- iina/MainWindowController.swift
- iina/MenuController.swift
- iina/MiniPlayerWindowController.swift
- iina/OnlineSubtitle.swift
- iina/OpenSubSubtitle.swift
- iina/PlayerCore.swift
- iina/Preference.swift
- iina/SleepPreventer.swift
- iina/ThumbnailCache.swift
- iina/Utility.swift
- iina/ViewLayer.swift
> Revised Logging System

- iina.xcodeproj/project.pbxproj
- iina/ko.lproj/Contribution.rtf
- iina/ko.lproj/FontPickerWindowController.strings
- iina/ko.lproj/InitialWindowController.strings
- iina/ko.lproj/Localizable.strings
- iina/ko.lproj/MainMenu.strings
- iina/ko.lproj/PrefAdvancedViewController.strings
- iina/ko.lproj/PrefCodecViewController.strings
- iina/ko.lproj/PrefControlViewController.strings
- iina/ko.lproj/PrefGeneralViewController.strings
- iina/ko.lproj/PrefKeyBindingViewController.strings
- iina/ko.lproj/PrefOSCToolbarSettingsSheetController.strings
- iina/ko.lproj/PrefSubViewController.strings
- iina/ko.lproj/PrefUIViewController.strings
- iina/ko.lproj/PrefUtilsViewController.strings
- iina/ko.lproj/PreferenceWindowController.strings
> Korean Translation: Localization for 1.0.0 Beta 3

- .editorconfig
> Update .editorconfig file

- iina/MPVController.swift
- iina/PlaybackInfo.swift
- iina/PlayerCore.swift
- iina/QuickSettingViewController.swift
> Make audio eq works again

- iina/FilterWindowController.swift
- iina/PrefAdvancedViewController.swift
- iina/PrefKeyBindingViewController.swift
- iina/PrefSubViewController.swift
- iina/PrefUtilsViewController.swift
- iina/Utility.swift
Change all alert which are not initialized by MainWindow to sheet alert
> Add sheet window parameter to showAlert method

- iina-cli/main.swift
- iina/AppDelegate.swift
- iina/MPVController.swift
- iina/PlayerCore.swift
- Fixed `ontop` and `fullscreen` not working for CLI (#1891)
- Fixed CLI handling multiple remote URLs incorrectly (#1706)
- Added `--keep-running` (#1856) and `--pip` (#1856, #1386) for CLI
- New URL scheme and more options (#379, #1136)
> New URL scheme and more CLI options

- iina.xcodeproj/project.pbxproj
- iina/it.lproj/OpenURLWindowController.strings
Italian localization for OpenURLWindowcController.xib
> Italian Localization OpenURLWindowcController.xib 1.0.0 beta4

- iina/MainWindowController.swift
- iina/PlayerCore.swift
- iina/VideoView.swift
> Stop displaylink when not playing

- iina/MainWindowController.swift
- iina/OSDMessage.swift
- iina/de.lproj/AboutWindowController.strings
- iina/de.lproj/FontPickerWindowController.strings
- iina/de.lproj/Localizable.strings
- iina/de.lproj/PrefGeneralViewController.strings
- iina/de.lproj/PrefUIViewController.strings
> Update de localization

- iina/fr.lproj/AboutWindowController.strings
- iina/fr.lproj/FontPickerWindowController.strings
- iina/fr.lproj/InitialWindowController.strings
- iina/fr.lproj/KeyBinding.strings
- iina/fr.lproj/Localizable.strings
- iina/fr.lproj/MainMenu.strings
- iina/fr.lproj/PlaylistViewController.strings
- iina/fr.lproj/PrefGeneralViewController.strings
- iina/fr.lproj/PrefSubViewController.strings
- iina/fr.lproj/PrefUIViewController.strings
- iina/fr.lproj/QuickSettingViewController.strings
---
`check_translation.swift` returns 0 issues.
> updated french translation for 1.0.0

- iina/Base.lproj/AboutWindowController.xib
> Enable selectable for version labels in about window.

- README.md
> fixed compile

- iina/Base.lproj/MainMenu.xib
- iina/DraggingDetect.swift
- iina/PlayerCore.swift
- iina/PlaylistViewController.swift
This PR make playlist support edit menu (copy, cut, paste, delete).
> Add support edit menu support for playlist

- .travis.yml
- iina.xcodeproj/xcshareddata/xcschemes/iina-cli.xcscheme
---
- Ensure each pull request is valid and could pass unit testing (future?) before merging into the `develop` branch. Always keep the main branch under a buildable state.
- Keep the build fast, self-testing and automatic. Make workflow simpler to create a nightly/alpha/beta build using CI Cron Jobs.
- Integrate automatic linting (future?) to avoid syntax inconsistencies and common style mistakes.
- Make a pull request.
- You're all set! Leave it to CI and reviewers.
> Continuous Integration w/ Travis

- CONTRIBUTING.md
- README.md
---
Just tweaking some wording, so I thought I'd just run this through a pull request so people can give their feedback if they want. I'm planning on merging this in a couple days if nobody raises any issues.
> Tweak prose to be more clear and inviting

- README.md
---
Updated telegram group link
> Updated telegram group link

- iina/Translators.json
> Add @ailtonvivaz into translators (pt-BR)

- iina/ko.lproj/Localizable.strings
- iina/ko.lproj/PrefUIViewController.strings
> Korean localization for 1.0.2 release

- iina/it.lproj/Localizable.strings
- iina/it.lproj/MainWindowController.strings
- iina/it.lproj/PrefUIViewController.strings
Italian localization for 1.0.2 Release #2285
> [it] Italian l11n for 1.0.2 Release

- iina/ro.lproj/Localizable.strings
- iina/ro.lproj/MainWindowController.strings
- iina/ro.lproj/PrefUIViewController.strings
updated the required strings and fixed some old typos
---
> Romanian localization updates for 1.0.2

- iina/es.lproj/Localizable.strings
- iina/es.lproj/PrefUIViewController.strings
spanish translations for:
- Preferences > UI > Picture-in-Picture (#2192)
- "pl_menu.browser", "pl_menu.copy_url", "pl_menu.copy_url_multi" in localizable.strings (#2271)
- "touchbar.toggle_pip" in localizable.strings (#1900)
> spanish translation 1.0.2

- iina/pt-BR.lproj/Localizable.strings
> Updated Brazilian Portuguese locaization for 1.0.2

- .travis.yml
> pod update before ci

- iina.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- iina/ru.lproj/Localizable.strings
- iina/ru.lproj/PrefUIViewController.strings
> updated Russian translation for 1.0.2

- iina/AppData.swift
- iina/Base.lproj/PrefKeyBindingViewController.xib
- iina/FontPickerWindowController.swift
- iina/KeyMapping.swift
- iina/PrefKeyBindingViewController.swift
- iina/Preference.swift
This PR rewrite the data source of Key binding table view (in order to utilize the bindings between NSSearchBar and NSArrayController).
Ref: #2241
> Add a search bar to filter key bindings

- README.md
- other/change_lib_dependencies.rb
---
Updates to the build process to accommodate alternative methods of building dependencies. The specifics of the changes are up for discussion (I don't actually know Ruby, lol), but I hope that the intent is clear.
> Improve library management stuff

- iina/de.lproj/Localizable.strings
- iina/de.lproj/PrefCodecViewController.strings
- iina/de.lproj/PrefUIViewController.strings
> Updated German translation

- iina/PlayerCore.swift
> Fixes miniplayer playtime slider and labels not updating on network resources

- iina/Translators.json
> Request translator status for German

- README.md
---
I couldn't find `deps/libs` so I'm assuming `deps/lib`.
> Correct directory names in readme

- iina/pl.lproj/Localizable.strings
> Update Localizable.strings for Polish language

- iina/en.lproj/AboutWindowController.strings
- iina/en.lproj/CropSettingsViewController.strings
- iina/en.lproj/FilterPresets.strings
- iina/en.lproj/FilterWindowController.strings
- iina/en.lproj/FontPickerWindowController.strings
- iina/en.lproj/HistoryWindowController.strings
- iina/en.lproj/InitialWindowController.strings
- iina/en.lproj/InspectorWindowController.strings
- iina/en.lproj/KeyBinding.strings
- iina/en.lproj/Localizable.strings
- iina/en.lproj/MainMenu.strings
- iina/en.lproj/MainWindowController.strings
- iina/en.lproj/MiniPlayerWindowController.strings
- iina/en.lproj/OpenURLWindowController.strings
- iina/en.lproj/PlaylistViewController.strings
- iina/en.lproj/PrefAdvancedViewController.strings
- iina/en.lproj/PrefCodecViewController.strings
- iina/en.lproj/PrefGeneralViewController.strings
- iina/en.lproj/PrefKeyBindingViewController.strings
- iina/en.lproj/PrefNetworkViewController.strings
- iina/en.lproj/PrefOSCToolbarSettingsSheetController.strings
- iina/en.lproj/PrefSubViewController.strings
- iina/en.lproj/PrefUIViewController.strings
- iina/en.lproj/PreferenceWindowController.strings
- iina/en.lproj/QuickSettingViewController.strings
- iina/en.lproj/SubChooseViewController.strings
We are going to use [crowdin.com](https://crowdin.com) to do the localization in the future. Everyone who is interested in helping localize or improve the current localiztion can visit [translate.iina.io](https://translate.iina.io) and register an account for free.
Crowdin has an elegent way to show the completeness of each language, compare to the base language. This PR removes the strings that are not needed to be translated, so that Crowdin can give us a better completeness of each language.
Please help me to find any string that shouldn't be removed in this PR, thanks!
> Clean up string files for the base language (en)

- iina/tr.lproj/HistoryWindowController.strings
- iina/tr.lproj/InitialWindowController.strings
- iina/tr.lproj/InspectorWindowController.strings
- iina/tr.lproj/MainMenu.strings
- iina/tr.lproj/PlaylistViewController.strings
- iina/tr.lproj/PrefCodecViewController.strings
- iina/tr.lproj/PrefControlViewController.strings
- iina/tr.lproj/PrefGeneralViewController.strings
- iina/tr.lproj/PrefSubViewController.strings
- iina/tr.lproj/SubChooseViewController.strings
> Turkish Translation Corrections

- iina/Base.lproj/PrefControlViewController.xib
- iina/Preference.swift
- iina/VideoView.swift
- iina/en.lproj/PrefControlViewController.strings
> Add a option to accept first mouse or not

- iina/en.lproj/PrefGeneralViewController.strings
Some minor changes to the grammar and syntax of various phrases in the General part of the main preferences window.
> Changes to grammar and syntax of General prefs

- iina/Translators.json
Quick pull request because my GitHub username has changed. This updates the entry in `Translators.json`.
> Translator: Username changed

- iina/AppDelegate.swift
> Fix typo in AppDelegate file

- iina/zh-Hant.lproj/Contribution.rtf
Change font PingFang SC to PingFang TC
---
> Change font PingFang SC to PingFang TC

- iina/Base.lproj/PlaylistViewController.xib
- iina/Base.lproj/PrefGeneralViewController.xib
- iina/Base.lproj/PrefUIViewController.xib
- iina/FFmpegController.h
- iina/FFmpegController.m
- iina/PlaybackInfo.swift
- iina/PlayerCore.swift
- iina/PlayerWindowController.swift
- iina/PlaylistViewController.swift
- iina/Preference.swift
- Add an option to show `[artist - title]` in the playlist instead of the filename (for audio files)
- Add an option to do so only in the music mode
> Show metadata (artist - title) in the playlist

- iina/AppData.swift
- iina/Base.lproj/Localizable.strings
- iina/MainMenuActions.swift
- iina/MenuController.swift
- iina/en.lproj/Localizable.strings
---
Added the "custom" button under [Video] - [Crop].
> Supports "custom" crop size in the main menu bar.

- README.md
---
Either I'm wrong or the word "considates" doesn't exist.
> replace considates with consolidates

- iina/MPVController.swift
- iina/PlaybackInfo.swift
- iina/PlayerCore.swift
- iina/PlaylistViewController.swift
This PR is from #3479. The code in the previous PR won't compile and I added a missing method call.
It fixes issue #3405.
> Low batt fix 3405

- iina/PlayerCore.swift
The commit in the pull request corrects a crash due to a
NSInvalidArgumentException being thrown by the
NowPlayingInfoManager.updateInfo method as a result of multiple threads
changing the same dictionary at the same time. The commit updates the
NowPlayingInfoManager class to be thread safe.
---
> Fix NSInvalidArgumentException crash, #3584

- iina/PlayerCore.swift
---
Seems that we can only use the raw key `"com.apple.lastuseddate#PS"`. P and S are `XATTR_FLAG_NO_EXPORT` and `XATTR_FLAG_SYNCABLE` flags ([ref](https://opensource.apple.com/source/copyfile/copyfile-138/xattr_flags.c.auto.html)).
> Update "data last opened" attribute on file start

- iina/config/input.conf
---
Resubmitting with only input.conf updated
> Fix for #3718: Merge changes from MPV 0.34's input.conf

- iina/PlayerCore.swift
> Plugin: fix event.on "iina.file-loaded" url type URL => String

- iina/OpenSubSubtitle.swift
Includes the fixes for #3907 and #3908, based on the code by @low-batt.
---
See the corresponding issues.
> OpenSubtitles: fix episode guessing

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- Updated the pull request template
- Remove pod related stuff in contributing.md
- Add explanation on localization in contributing.md
> Update pull request template and contributing.md

- iina/DurationDisplayTextField.swift
> Update rightLabel when clicked while player paused

- iina/Base.lproj/PrefCodecViewController.xib
- iina/PlayerCore.swift
- iina/Preference.swift
- iina/en.lproj/PrefCodecViewController.strings
---
Since this contains mostly xib changes, redo instead of cherrypicking.
Remake of https://github.com/iina-plus/iina/commit/0cae12493370e2f7d8c59ae007bfaabe4f0b99c3
> Add an HDR killswitch in the preferences
